### PR TITLE
Check errors before using l0 kernel pointer

### LINKED ISSUE #428: Errors not being surfaced after move to SYCL backend
Cases that used to return errors now are segfaulting. Looks like we are missing some error checking in one of the new driver functions.

### PR DESCRIPTION
**Pull request by alexbaden**
Checks for stored runtime error before using l0 kernel call. I suppose we could also check for a nullptr in the l0 kernel handle but it seems redundant - an assert would be nice, but I did not see other c code using asserts. I copied the additional lines around the GIL from upstream nvidia backend - it appears that was added as part of a recent bug fix. 

After this call we are once again properly surfacing L0 errors:
``` 
FAILED test_core.py::test_locality[4-2048-64-sum] - RuntimeError: Triton Error [ZE]: 2013265944
```

Closes #428

### CODE REVIEW

File: third_party/intel/backend/driver.c [hunk 1]
```diff
@@ -226,8 +229,14 @@ static PyObject *loadSyclBinary(PyObject *self, PyObject *args) {
   auto l0_context = sycl::get_native<sycl::backend::ext_oneapi_level_zero>(ctx);
   auto l0_module =
       create_module(l0_context, l0_device, binary_ptr, binary_size);
-
+
```
Comment (whitneywhtsang) [inline third_party/intel/backend/driver.c:232]:
```suggestion

```

**Review by whitneywhtsang — APPROVED** [review]
LGTM, thanks for fixing it.
