### PR TITLE
[LoadStoreOpToLLVM] Fix load with `base height == 1`

### LINKED ISSUE #4593: `python test/inductor/test_max_autotune.py TestPrologueFusion.test_mismatched_prologue_group` failed
From: https://github.com/intel/intel-xpu-backend-for-triton/pull/4592

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/15920652202/job/44906518398?pr=4592

Reproducer:
<details>

```python
# AOT ID: ['0_inference']
from ctypes import c_void_p, c_long, c_int
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from cmath import nanj
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile
from torch._inductor.codegen.memory_planning import _align as align
from torch import device, empty_strided
from torch._inductor.async_compile import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import start_graph, end_graph
from torch._C import _xpu_getCurrentRawStream as get_raw_stream
from torch._C import _xpu_getCurrentRawStream as get_raw_stream
from torch._inductor.utils import run_and_get_code

aten = torch.ops.aten
inductor_ops = torch.ops.inductor
_quantized = torch.ops._quantized
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
assert_alignment = torch._C._dynamo.guards.assert_alignment
empty_strided_cpu = torch._C._dynamo.guards._empty_strided_cpu
empty_strided_cuda = torch._C._dynamo.guards._empty_strided_cuda
empty_strided_xpu = torch._C._dynamo.guards._empty_strided_xpu
reinterpret_tensor = torch._C._dynamo.guards._reinterpret_tensor
alloc_from_pool = torch.ops.inductor._alloc_from_pool
async_compile = AsyncCompile()
empty_strided_p2p = torch._C._distributed_c10d._SymmetricMemory.empty_strided_p2p


# kernel path: /tmp/tmpop2bbzpz/xr/cxrb2fzcovzcryb3vp7enl77qbe7eqqonjmubolvk2znm7ic53v4.py
# Topologically Sorted Source Nodes: [add, a], Original ATen: [aten.add, aten.mul]
# Source node to ATen node mapping:
#   a => mul
#   add => add
# Graph fragment:
#   %add : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%arg0_1, 2), kwargs = {})
#   %mul : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%add, 2), kwargs = {})
triton_poi_fused_add_mul_0 = async_compile.triton('triton_poi_fused_add_mul_0', '''
import triton
import triton.language as tl

from torch._inductor.runtime import triton_helpers, triton_heuristics
from torch._inductor.runtime.triton_helpers import libdevice, math as tl_math
from torch._inductor.runtime.hints import AutotuneHint, ReductionHint, TileHint, DeviceProperties
triton_helpers.set_driver_to_gpu()

@triton_heuristics.pointwise(
    size_hints={'x': 256}, 
    filename=__file__,
    triton_meta={'signature': {'in_ptr0': '*fp32', 'out_ptr0': '*fp32', 'xnumel': 'i32', 'XBLOCK': 'constexpr'}, 'device': DeviceProperties(type='xpu', index=0, multi_processor_count=56, cc={'architecture': 13136561920, 'driver_version': '1.6.33276+22', 'gpu_eu_count': 448, 'gpu_subslice_count': 56, 'has_atomic64': True, 'has_bfloat16_conversions': True, 'has_fp16': True, 'has_fp64': True, 'has_subgroup_2d_block_io': True, 'has_subgroup_matrix_multiply_accumulate': True, 'has_subgroup_matrix_multiply_accumulate_tensor_float32': False, 'max_compute_units': 448, 'max_num_sub_groups': 64, 'max_work_group_size': 1024, 'name': 'Intel(R) Data Center GPU Max 1100', 'platform_name': 'Intel(R) oneAPI Unified Runtime over Level-Zero', 'sub_group_sizes': [16, 32], 'total_memory': 51522830336, 'type': 'gpu', 'vendor': 'Intel(R) Corporation', 'version': '12.60.7'}, major=None, regs_per_multiprocessor=None, max_threads_per_multi_processor=None, warp_size=32), 'constants': {}, 'configs': [{(0,): [['tt.divisibility', 16]], (1,): [['tt.divisibility', 16]], (2,): [['tt.divisibility', 16]]}]},
    inductor_meta={'grid_type': 'Grid1D', 'autotune_hints': set(), 'kernel_name': 'triton_poi_fused_add_mul_0', 'mutated_arg_names': [], 'optimize_mem': True, 'no_x_dim': False, 'num_load': 1, 'num_reduction': 0, 'backend_hash': 'A7B814AC5CFF905E49DD4895009ABE908357D70215B83E5102B8A43F0482A8B8', 'are_deterministic_algorithms_enabled': False, 'assert_indirect_indexing': True, 'autotune_local_cache': True, 'autotune_pointwise': True, 'autotune_remote_cache': None, 'force_disable_caches': False, 'dynamic_scale_rblock': True, 'max_autotune': True, 'max_autotune_pointwise': False, 'min_split_scan_rblock': 256, 'spill_threshold': 16, 'store_cubin': False, 'tiling_scores': {'x': 3072}},
    min_elem_per_thread=0
)
@triton.jit
def triton_poi_fused_add_mul_0(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 256
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = 2.0
    tmp2 = tmp0 + tmp1
    tmp3 = tmp2 * tmp1
    tl.store(out_ptr0 + (x0), tmp3, xmask)
''', device_str='xpu')


# kernel path: /tmp/tmpop2bbzpz/zc/czcsgxabfh5wmz7rre2zahygid2uvx3ohstnt3rkqz32fuztlarx.py
# Topologically Sorted Source Nodes: [add, a, b, matmul], Original ATen: [aten.add, aten.mul, aten.mm]
# Source node to ATen node mapping:
#   a => mul
#   add => add
#   b => mul_1
#   matmul => mm
# Graph fragment:
#   %add : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%arg0_1, 2), kwargs = {})
#   %mul : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%add, 2), kwargs = {})
#   %mul_1 : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%mul, %arg1_1), kwargs = {})
#   %mm : [num_users=1] = call_function[target=torch.ops.aten.mm.default](args = (%mul_1, %arg2_1), kwargs = {})
triton_tem_fused_add_mm_mul_1 = async_compile.triton('triton_tem_fused_add_mm_mul_1', '''
import triton
import triton.language as tl

from torch._inductor.runtime import triton_helpers, triton_heuristics
from torch._inductor.runtime.triton_helpers import libdevice, math as tl_math
from torch._inductor.runtime.hints import AutotuneHint, ReductionHint, TileHint, DeviceProperties

@triton_heuristics.template(

num_stages=5,
num_warps=8,
triton_meta={'signature': {'arg_B': '*fp32', 'in_ptr1': '*fp32', 'in_ptr2': '*fp32', 'out_ptr0': '*fp32'}, 'device': DeviceProperties(type='xpu', index=0, multi_processor_count=56, cc={'architecture': 13136561920, 'driver_version': '1.6.33276+22', 'gpu_eu_count': 448, 'gpu_subslice_count': 56, 'has_atomic64': True, 'has_bfloat16_conversions': True, 'has_fp16': True, 'has_fp64': True, 'has_subgroup_2d_block_io': True, 'has_subgroup_matrix_multiply_accumulate': True, 'has_subgroup_matrix_multiply_accumulate_tensor_float32': False, 'max_compute_units': 448, 'max_num_sub_groups': 64, 'max_work_group_size': 1024, 'name': 'Intel(R) Data Center GPU Max 1100', 'platform_name': 'Intel(R) oneAPI Unified Runtime over Level-Zero', 'sub_group_sizes': [16, 32], 'total_memory': 51522830336, 'type': 'gpu', 'vendor': 'Intel(R) Corporation', 'version': '12.60.7'}, major=None, regs_per_multiprocessor=None, max_threads_per_multi_processor=None, warp_size=32), 'constants': {}, 'configs': [{(0,): [['tt.divisibility', 16]], (1,): [['tt.divisibility', 16]], (2,): [['tt.divisibility', 16]], (3,): [['tt.divisibility', 16]]}]},
inductor_meta={'kernel_name': 'triton_tem_fused_add_mm_mul_1', 'backend_hash': 'A7B814AC5CFF905E49DD4895009ABE908357D70215B83E5102B8A43F0482A8B8', 'are_deterministic_algorithms_enabled': False, 'assert_indirect_indexing': True, 'autotune_local_cache': True, 'autotune_pointwise': True, 'autotune_remote_cache': None, 'force_disable_caches': False, 'dynamic_scale_rblock': True, 'max_autotune': True, 'max_autotune_pointwise': False, 'min_split_scan_rblock': 256, 'spill_threshold': 16, 'store_cubin': False, 'grid_type': 'FixedGrid', 'fixed_grid': ['_grid_0', '_grid_1', '_grid_2'], 'extra_launcher_args': ['_grid_0', '_grid_1', '_grid_2']},

)
@triton.jit
def triton_tem_fused_add_mm_mul_1(arg_B, in_ptr1, in_ptr2, out_ptr0):
    EVEN_K : tl.constexpr = True
    ALLOW_TF32 : tl.constexpr = True
    USE_FAST_ACCUM : tl.constexpr = False
    ACC_TYPE : tl.constexpr = tl.float32
    BLOCK_M : tl.constexpr = 64
    BLOCK_N : tl.constexpr = 32
    BLOCK_K : tl.constexpr = 32
    GROUP_M : tl.constexpr = 8
    B = arg_B

    M = 256
    N = 128
    K = 256
    if M * N == 0:
        # early exit due to zero-size input(s)
        return
    stride_am = 256
    stride_ak = 1
    stride_bk = 128
    stride_bn = 1

    # based on triton.ops.matmul
    pid = tl.program_id(0)
    grid_m = (M + BLOCK_M - 1) // BLOCK_M
    grid_n = (N + BLOCK_N - 1) // BLOCK_N

    # re-order program ID for better L2 performance
    width = GROUP_M * grid_n
    group_id = pid // width
    group_size = min(grid_m - group_id * GROUP_M, GROUP_M)
    pid_m = group_id * GROUP_M + (pid % group_size)
    pid_n = (pid % width) // (group_size)
    tl.assume(pid_m >= 0)
    tl.assume(pid_n >= 0)

    rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    rn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    if ((stride_am == 1 and stride_ak == M) or (stride_am == K and stride_ak == 1)) and M >= BLOCK_M:
        offs_a_m = tl.max_contiguous(tl.multiple_of(rm % M, BLOCK_M), BLOCK_M)
    else:
        offs_a_m = rm % M
    if ((stride_bk == 1 and stride_bn == K) or (stride_bk == N and stride_bn == 1)) and N >= BLOCK_N:
        offs_b_n = tl.max_contiguous(tl.multiple_of(rn % N, BLOCK_N), BLOCK_N)
    else:
        offs_b_n = rn % N
    offs_k = tl.arange(0, BLOCK_K)
    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=ACC_TYPE)

    for k_idx in range(0, tl.cdiv(K, BLOCK_K)):

        a_k_idx_vals = offs_k[None, :] + (k_idx * BLOCK_K)
        b_k_idx_vals = offs_k[:, None] + (k_idx * BLOCK_K)

        idx_m = offs_a_m[:, None]
        idx_n = a_k_idx_vals
        xindex = idx_n + 256*idx_m
        tmp0 = tl.load(in_ptr1 + (tl.broadcast_to(idx_n, xindex.shape)), None, eviction_policy='evict_last')
        tmp1 = tl.load(in_ptr2 + (tl.broadcast_to(idx_n + 256*idx_m, xindex.shape)), None, eviction_policy='evict_last')
        tmp2 = tmp0 * tmp1
        a = tmp2.broadcast_to(xindex.shape)

        idx_m = b_k_idx_vals
        idx_n = offs_b_n[None, :]
        xindex = idx_n + 128*idx_m
        b = tl.load(B + (xindex))


        acc += tl.dot(a, b, allow_tf32=ALLOW_TF32, out_dtype=ACC_TYPE)


    # rematerialize rm and rn to save registers
    rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    rn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    idx_m = rm[:, None]
    idx_n = rn[None, :]
    mask = (idx_m < M) & (idx_n < N)

    # inductor generates a suffix
    xindex = idx_n + 128*idx_m
    tl.store(out_ptr0 + (tl.broadcast_to(xindex, acc.shape)), acc, mask)
''', device_str='xpu')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1, arg2_1 = args
    args.clear()
    assert_size_stride(arg0_1, (1, 256), (256, 1))
    assert_size_stride(arg1_1, (256, 256), (256, 1))
    assert_size_stride(arg2_1, (256, 128), (128, 1))
    with torch.xpu._DeviceGuard(0):
        torch.xpu.set_device(0)
        buf0 = empty_strided_xpu((1, 256), (256, 1), torch.float32)
        # Topologically Sorted Source Nodes: [add, a], Original ATen: [aten.add, aten.mul]
        stream0 = get_raw_stream(0)
        triton_poi_fused_add_mul_0.run(arg0_1, buf0, 256, stream=stream0)
        del arg0_1
        buf2 = empty_strided_xpu((256, 128), (128, 1), torch.float32)
        # Topologically Sorted Source Nodes: [add, a, b, matmul], Original ATen: [aten.add, aten.mul, aten.mm]
        stream0 = get_raw_stream(0)
        triton_tem_fused_add_mm_mul_1.run(arg2_1, buf0, arg1_1, buf2, 16, 1, 1, stream=stream0)
        del arg1_1
        del arg2_1
        del buf0
    return (buf2, )


def benchmark_compiled_module(times=10, repeat=10):
    arg0_1 = torch.rand([1, 256], device='xpu')
    arg1_1 = torch.rand([256, 256], device='xpu')
    arg2_1 = torch.rand([256, 128], device='xpu')
    fn = lambda: call([arg0_1, arg1_1, arg2_1])
    def foo(x, y, z):
        a = (x + 2) * 2
        b = a * y
        return b @ z

    out = foo(arg0_1, arg1_1, arg2_1)
    torch.testing.assert_close(fn()[0], foo(arg0_1, arg1_1, arg2_1), atol=0.05, rtol=0.05)


if __name__ == "__main__":
    benchmark_compiled_module()

```
</details>

### PR DESCRIPTION
**Pull request by whitneywhtsang**
When `strides[0]` is 0, we only want to load the first row, so we set the base height to be 1. (<= done in another PR)
When base height is less than tile height and base height is 1, only the first row contain valid data. 
To ensure the entire tile is filled with valid data, we must replicate the first row throughout the tile.

Benchmark CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/16004699061 (no geomean regression)
Inductor CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/16041054719 (passes)

New changes:
Benchmark CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/16041041775

Fixes #4593

### CODE REVIEW

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp [hunk 1]
```diff
@@ -1253,6 +1254,50 @@ struct LoadOpToBlockIOConversion
...
+                    // Since tile width is 2x threads per warp, we only need to
+                    // perform special handling when base height is 1.
+                    if (baseHeightInt == 1) {
+                      Value idx = b.i32_val(valueIndex);
+                      Value oldVal = b.extract_element(ret, idx);
+                      Value threadId = getThreadId(rewriter, loc);
+                      Value newVal = targetInfo.shuffleIdx(
+                          rewriter, loc, oldVal,
+                          b.urem(threadId, b.i32_val(tileWidth)));
+                      ret = b.insert_element(ret.getType(), ret, newVal, idx);
```
Comment (chengjunlu) [inline third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp]: Actually we want to broadcast the first row of the matrix to the entire matrix.
The in-place insertion might make the intention not so transparent. 

Maybe better to define a new matrix with the first value of the row and broadcast it to the matrix. The dummy operations generated by pack/unpack, insert/extract, and the `shuffleIndex` later can be eliminate easily.

File: test/TritonIntelGPU/tensor-pointer-load-block-2d.mlir [hunk 2]
```diff
@@ -246,3 +246,44 @@ module attributes {ttig.support_sg_2d_block, "ttg.num-warps" = 8 : i32} {
...
+    %19 = tt.expand_dims %18 {axis = 0 : i32} : tensor<32xi32, #ttg.slice<{dim = 0, parent = #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>}>> -> tensor<1x32xi32, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>>
+    %20 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<1x32x!tt.ptr<f32>, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>>
+    %21 = tt.addptr %20, %19 : tensor<1x32x!tt.ptr<f32>, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>>, tensor<1x32xi32, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>>
+    %22 = tt.broadcast %21 : tensor<1x32x!tt.ptr<f32>, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>> -> tensor<64x32x!tt.ptr<f32>, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>>
+    %50 = tt.load %22 {ttig.block_io = "row_major"} : tensor<64x32x!tt.ptr<f32>, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 1}>>
+    // CHECK: [[C1:%.*]] = llvm.mlir.constant(1 : i32) : i32
+    // CHECK: [[LOAD:%.*]] = triton_gen.2Dblockload %{{.*}}, %{{.*}}, [[C1]], %{{.*}}, %{{.*}}, %{{.*}} {elem_size_in_bits = 32, tile_width = 8, tile_height = 16, v_blocks = 2
```
Comment (etiotto) [inline test/TritonIntelGPU/tensor-pointer-load-block-2d.mlir:264]: what is the tile width here ? What happens when the tile width is larger than the base width?

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp (hunk 1 above)
Comment (etiotto) [reply third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp]: why do we want to broadcast only the first matrix row rather than broadcasting all of the valid (base height) rows to the rest of the tile ?

File: test/TritonIntelGPU/tensor-pointer-load-block-2d.mlir (hunk 2 above)
Comment (whitneywhtsang) [reply test/TritonIntelGPU/tensor-pointer-load-block-2d.mlir:264]:
```
    Value baseWidth =
        b.i32_val(std::max(64u, vBlocks * tileWidth * (elemSizeInBits / 8)));
```
so base width cannot be smaller than tile width for tensor of pointer.

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp (hunk 1 above)
Comment (whitneywhtsang) [reply third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp]: > why do we want to broadcast only the first matrix row rather than broadcasting all of the valid (base height) rows to the rest of the tile ?

This code is specifically designed for `base height == 1`.

**Comment by anmyachev** [comment]
Inductor CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/16031070286 (passes)

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp (hunk 1 above)
Comment (whitneywhtsang) [reply third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp]: > Maybe better to define a new matrix

done
