### PR TITLE
Fix math::FmaOp lowering for XPU.

### LINKED ISSUE #755: [test_core.py::test_math_erf_op/test_math_fma_op] fails to run correctly on PVC
To reproduce, remove:
```
    if is_xpu():
        pytest.skip("FIXME: Fails to run on XPU")
```
and run:
`python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_math_erf_op`
`python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_math_fma_op`

### PR DESCRIPTION
**Pull request by ienkovich**
This patch enables Triton lowering for `math::FmaOp` instead of the default one to have proper values packing/unpacking on XPU.

Resolves #755

### CODE REVIEW

File: third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp [hunk 1]
```diff
@@ -2480,6 +2480,9 @@ void populateElementwiseOpToLLVMPatterns(
   POPULATE_UNARY_OP(triton::PtrToIntOp, LLVM::PtrToIntOp)
 #undef POPULATE_UNARY_OP
 
+  patterns.add<ElementwiseOpConversion<math::FmaOp, LLVM::FMAOp>>(
```
Comment (whitneywhtsang) [inline third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp:2483]: What is math::FmaOp lower to by default?

Comment (ienkovich) [reply third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp:2483]: It is lowered to the same op, but proper args unpacking is not added, so the resulting FMA operation gets `!llvm.struct<(f32)>` instead of `f32`, and later compilation fails. `ElementwiseOpConversionBase` pattern has a code to unpack values from the structures and pack the result back.

**Review by whitneywhtsang — APPROVED** [review]
