### PR TITLE
Fix upstream pytorch installation from nightly builds in the `compile-pytorch-ipex` script

### LINKED ISSUE #1949: Fix upstream pytorch installation from nightly builds in the `compile-pytorch-ipex` script
When trying to install pinned upstream Pytorch, the IPEX version is installed:

```bash
scripts/compile-pytorch-ipex.sh --upstream-pytorch --pinned
```

### PR DESCRIPTION
**Pull request by Retribution98**
Closes #1949

- [x] I am not making a trivial change, such as fixing a typo in a comment.

- [x] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
  - [x] This PR does not need a test because `FILL THIS IN`.

- Select one of the following.
  - [x] I have not added any `lit` tests.
  - [ ] The `lit` tests I have added follow these [best practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
    including the "tests should be minimal" section. (Usually running Python code
    and using the instructions it generates is not minimal.)

### CODE REVIEW

File: scripts/compile-pytorch-ipex.sh [hunk 1]
```diff
@@ -171,6 +171,15 @@ if [ "$BUILD_PINNED" = false ]; then
...
 if [ "$BUILD_FROM_SOURCE" = false ]; then
+  # FIXME https://github.com/intel/intel-xpu-backend-for-triton/issues/1894
+  if [ "$UPSTREAM_PYTORCH" = true || "$NO_OP_IPEX" = true ]; then
+    echo "**** Installing upstream PyTorch and noop IPEX from the nightly builds is not available now. Use '--source' to do this. ****"
+    exit 1
+  fi
+  if [ "$BUILD_PINNED" = true ]; then
+    echo "**** Installing pinned version of PyTorch from the nightly builds is not available now. ****"
+    exit 1
+  fi
```
Comment (anmyachev) [inline scripts/compile-pytorch-ipex.sh:182]: As far as I understand, it is implicitly assumed that the already assembled wheels are just for the pinned versions (just not for the upstream ones)

```suggestion
```

Comment (Retribution98) [reply scripts/compile-pytorch-ipex.sh:182]: Yes, but if your branch is no longer up to date, it will install a newer version than expected. Is this ok?

Comment (anmyachev) [reply scripts/compile-pytorch-ipex.sh:182]: > Is this ok?

No, but apparently it happens rarely. You can add a check that the versions match (what was downloaded and what we are pinning)

Comment (vlad-penkin) [reply scripts/compile-pytorch-ipex.sh:182]: Nightly wheels will be available after
- #1913
is implemented during current iteration. There is no need to make temporary change

**Review by vlad-penkin — CHANGES_REQUESTED** [review]

**Comment by Retribution98** [comment]
@vlad-penkin is it ok now?

**Comment by vlad-penkin** [comment]
> @vlad-penkin is it ok now?

Why do we need this change after this PR merge:

- #1955

?

File: scripts/compile-pytorch-ipex.sh [hunk 2]
```diff
@@ -173,16 +184,28 @@ if [ "$BUILD_PINNED" = false ]; then
...
 if [ "$BUILD_FROM_SOURCE" = false ]; then
-  echo "**** Install PyTorch and IPEX from nightly builds. ****"
+  echo "**** Download nightly builds. ****"
   PYTHON_VERSION=$( python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" )
   RUN_ID=$(gh run list -w "Triton wheels" -R intel/intel-xpu-backend-for-triton --json databaseId,conclusion | jq -r '[.[] | select(.conclusion=="success")][0].databaseId')
   TEMP_DIR=$(mktemp -d)
+  WHEEL_PATTERN="wheels-py${PYTHON_VERSION}*"
+  if [ "$UPSTREAM_PYTORCH" = true ]; then
+    WHEEL_PATTERN="wheels-pytorch-py${PYTHON_VERSION}*"
+  fi
```
Comment (anmyachev) [inline scripts/compile-pytorch-ipex.sh:194]: Is this the only difference between upstream and proxy pytorch wheels?

**Review by anmyachev — APPROVED** [review]
LGTM!

File: scripts/compile-pytorch-ipex.sh (hunk 2 above)
Comment (Retribution98) [reply scripts/compile-pytorch-ipex.sh:194]: yes, but only for torch. 
ipex doesn't exist, so we need to build noop locally

**Comment by Retribution98** [comment]
> Why do we need this change after this PR merge:
@vlad-penkin 
Yes, this issue is now complete, but the script is still not working correctly.
I replaced the error by installing the correct version from the wheels

File: scripts/compile-pytorch-ipex.sh [hunk 3]
```diff
@@ -144,13 +144,24 @@ if [ "$BUILD_PINNED" = true ]; then
   BUILD_IPEX=true
   if pip show intel_extension_for_pytorch &>/dev/null; then
     IPEX_CURRENT_COMMIT=`python -c "import torch;import intel_extension_for_pytorch as ipex;print(ipex.__version__)"`
-    IPEX_CURRENT_COMMIT=${IPEX_CURRENT_COMMIT#*"git"}
-    if [[ "$IPEX_PINNED_COMMIT" = "$IPEX_CURRENT_COMMIT"* ]]; then
-      echo "**** IPEX is already installed and its current commit is equal to the pinned commit: $IPEX_PINNED_COMMIT. ****"
-      BUILD_IPEX=false
+    if [ "$NO_OP_IPEX" = true ]; then
+      IPEX_CURRENT_COMMIT=${IPEX_CURRENT_COMMIT#*"+"}
+      if [[ "noop" = "$IPEX_CURRENT_COMMIT"* ]]; then
```
Comment (pbchekin) [inline scripts/compile-pytorch-ipex.sh:149]: This does not work:

```
# prints nothing
IPEX_CURRENT_COMMIT="2.4.0+noop"
[[ "noop" = "$IPEX_CURRENT_COMMIT"* ]] && echo noop
```

This should work:

```
IPEX_CURRENT_COMMIT="2.4.0+noop"
[[ $IPEX_CURRENT_COMMIT = *noop ]] && echo noop
```

File: scripts/compile-pytorch-ipex.sh [hunk 4]
```diff
@@ -144,13 +144,24 @@ if [ "$BUILD_PINNED" = true ]; then
...
+        BUILD_IPEX=false
+      else
+        echo "**** Current IPEX commit $IPEX_CURRENT_COMMIT ****"
+        echo "**** Expected no-op IPEX ****"
+      fi
     else
-      echo "**** Current IPEX commit $IPEX_CURRENT_COMMIT ****"
-      echo "**** Pinned IPEX commit $IPEX_PINNED_COMMIT ****"
+      IPEX_CURRENT_COMMIT=${IPEX_CURRENT_COMMIT#*"git"}
+      if [[ "$IPEX_PINNED_COMMIT" = "$IPEX_CURRENT_COMMIT"* ]]; then
```
Comment (pbchekin) [inline scripts/compile-pytorch-ipex.sh:158]: If you use double square brackets, then quotes are not needed:
```suggestion
      if [[ $IPEX_PINNED_COMMIT = $IPEX_CURRENT_COMMIT* ]]; then
```

File: scripts/compile-pytorch-ipex.sh [hunk 5]
```diff
@@ -173,16 +184,28 @@ if [ "$BUILD_PINNED" = false ]; then
...
   RUN_ID=$(gh run list -w "Triton wheels" -R intel/intel-xpu-backend-for-triton --json databaseId,conclusion | jq -r '[.[] | select(.conclusion=="success")][0].databaseId')
   TEMP_DIR=$(mktemp -d)
+  WHEEL_PATTERN="wheels-py${PYTHON_VERSION}*"
+  if [ "$UPSTREAM_PYTORCH" = true ]; then
+    WHEEL_PATTERN="wheels-pytorch-py${PYTHON_VERSION}*"
+  fi
   gh run download $RUN_ID \
     --repo intel/intel-xpu-backend-for-triton \
-    --pattern "wheels-py${PYTHON_VERSION}*" \
+    --pattern $WHEEL_PATTERN \
```
Comment (pbchekin) [inline scripts/compile-pytorch-ipex.sh:197]: Just to be on the safe side:
```suggestion
    --pattern "$WHEEL_PATTERN" \
```
We don't want bash to interpolate WHEEL_PATTERN if there is a file or directory with the name that matches .

File: scripts/compile-pytorch-ipex.sh (hunk 3 above)
Comment (Retribution98) [reply scripts/compile-pytorch-ipex.sh:149]: I checked and it should work because the current commit is split on the 148 line and only the part after + remains
I believe we don't need to hardcode the expected version there, because is set in the other script.
Should we pin it like as IPEX version or can we check only "noop" suffix?

File: scripts/compile-pytorch-ipex.sh (hunk 4 above)
Comment (Retribution98) [reply scripts/compile-pytorch-ipex.sh:158]: I see. Thank you!

File: scripts/compile-pytorch-ipex.sh (hunk 5 above)
Comment (Retribution98) [reply scripts/compile-pytorch-ipex.sh:197]: Agree, thank you

**Comment by vlad-penkin** [comment]
> > Why do we need this change after this PR merge:
> 
> @vlad-penkin Yes, this issue is now complete, but the script is still not working correctly. I replaced the error by installing the correct version from the wheels

Can we rename the PR and the linked issue? Current titles are misguiding.

**Comment by Retribution98** [comment]
> Can we rename the PR and the linked issue? Current titles are misguiding.

@vlad-penkin
All is updated

**Comment by vlad-penkin** [comment]
Provided my feedback in https://github.com/intel/intel-xpu-backend-for-triton/issues/1949#issuecomment-2307899415.

**Review by AshburnLee — COMMENTED** [review]
I use your forked repo and branch, 
1. At least this use case fails on test:
~~~
./scritps/compile-triton.sh --clean
./scripts/compile-pytorch-ipex.sh --upstream-pytorch  --no-op-ipex --pinned
./scritps/test-triton.sh --no-deps --core
~~~

2. And in the following use case, the test script will build IPEX which is not expected:
~~~
./scritps/compile-triton.sh --clean
./scripts/compile-pytorch-ipex.sh --upstream-pytorch  --no-op-ipex --source
./scritps/test-triton.sh --no-deps --core  # will build IPEX
# log: **** Install IPEX from nightly builds. ****
~~~ 
`test-triton.sh` needs change accordingly.
Please give a further check.

I'll check other use cases.

File: scripts/compile-pytorch-ipex.sh [hunk 6]
```diff
@@ -144,13 +144,24 @@ if [ "$BUILD_PINNED" = true ]; then
...
+        BUILD_IPEX=false
+      else
+        echo "**** Current IPEX commit $IPEX_CURRENT_COMMIT ****"
+        echo "**** Expected no-op IPEX ****"
+      fi
     else
-      echo "**** Current IPEX commit $IPEX_CURRENT_COMMIT ****"
-      echo "**** Pinned IPEX commit $IPEX_PINNED_COMMIT ****"
+      IPEX_CURRENT_COMMIT=${IPEX_CURRENT_COMMIT#*"git"}
+      if [[ $IPEX_PINNED_COMMIT = $IPEX_CURRENT_COMMIT* ]]; then
```
Comment (pbchekin) [inline scripts/compile-pytorch-ipex.sh:158]: `IPEX_PINNED_COMMIT` is a full commit id, `IPEX_CURRENT_COMMIT` is a short commit id?
If this is the case then `[[ $IPEX_PINNED_COMMIT = $IPEX_CURRENT_COMMIT* ]]` won't work.

**Comment by Retribution98** [comment]
@AshburnLee thank you for you comment,
 
> At least this use case fails on test:
Unfortunately, I can not reproduce your fails, could you share what kind of errors you're getting?

But I see that you are using the wrong `--no-deps` parameter in both cases. The correct option is `--skip-deps`.
If the `--skip-deps` parameter is not given, the IPEX version from wheels is installed by default.

File: scripts/compile-pytorch-ipex.sh (hunk 6 above)
Comment (Retribution98) [reply scripts/compile-pytorch-ipex.sh:158]: `IPEX_PINNED_COMMIT` - the value from `./github/pins/ipex.txt`
`IPEX_CURRENT_COMMIT` - the value from the installed version.

In this PR, I'm keeping the previous behavior:
1. We get the full version name and put it in `IPEX_CURRENT_COMMIT`.
2. We then split the current value. 
    - If this version was built by the specific commit, we can get its hash and put it back into `IPEX_CURRENT_COMMIT`.
    - If IPEX was built from our `create-noop-ipex.py` script, the version has `noop` instead of the commit hash and we also put it into `IPEX_CURRENT_COMMIT`.

I agree that the variable name doesn't show the full picture of what's going on, but I think it was done to reuse the variable and not increase the number of variables. Do you suggest using an additional variable?

**Review by pbchekin — APPROVED** [review]

**Comment by vlad-penkin** [comment]
> @AshburnLee thank you for you comment,
> 
> > At least this use case fails on test:
> > Unfortunately, I can not reproduce your fails, could you share what kind of errors you're getting?
> 
> But I see that you are using the wrong `--no-deps` parameter in both cases. The correct option is `--skip-deps`. If the `--skip-deps` parameter is not given, the IPEX version from wheels is installed by default.

This behavior needs to be changed as part of this PR. Nightly PyTorch wheel should be installed by default.

**Comment by AshburnLee** [comment]
There are 4 use cases for this script:

1. Build upstream pytorch with branch dev/triton-test-3.0 & fake IPEX:
`./scripts/compile-pytorch-ipex.sh --upstream-pytorch (--no-op-ipex --source)`
IPEX version & torch version:
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.1.0a0+git4de5871  # pytorch branch: dev/triton-test-3.0

`test-triton.sh --skip-deps` faild:
```
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
```

2. Build upstream pytorch from pinned commit & fake IPEX
`./scripts/compile-pytorch-ipex.sh --upstream-pytorch --no-op-ipex --pinned`
IPEX version & torch version:
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+gitb7baa06   # pinned upstream-pytorch

`test-triton.sh --skip-deps` faild:
```
FAILED language/test_compile_errors.py::test_returns_branched_on_non_constexpr - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_global_var_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_binary_op - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_undefined_variable - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_builtin - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_not_const_annotate_no_err - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_static_assert - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_power_of_two_shapes_2 - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_power_of_two_shapes - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_constexpr_annotated_global_var_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_returns_branched_on_constexpr - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_binary_operator - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_captured_var_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_unary_op - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_two_returns_no_err - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_nested_call - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_constexpr_global_var_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_global_type_alias_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_defaults_assign_no_err - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_max_num_imprecise_acc_limit - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_global_access_in_fn_default_arg - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
ERROR language/test_annotations.py
ERROR language/test_block_pointer.py
ERROR language/test_conversions.py
ERROR language/test_core.py
ERROR language/test_decorator.py
ERROR language/test_emulated_atomics.py
ERROR language/test_libdevice.py
ERROR language/test_pipeliner.py
ERROR language/test_random.py
ERROR language/test_reproducer.py
ERROR language/test_standard.py
```

3. Build pytorch and IPEX from pinned commit
`./scripts/compile-pytorch-ipex.sh --pinned (--pytorch --ipex)`
IPEX version & torch version:
- intel-extension-for-pytorch 2.1.10+gitcd132db    # pinned
- torch                       2.1.0a0+git22ce6c6   # pinned

`test-triton.sh --skip-deps` pass


4. Build IPEX from pinned commit and pytorch from dev/triton-test-3.0
`./scripts/compile-pytorch-ipex.sh (--pytorch --ipex --source)`
IPEX version & torch version:
- intel_extension_for_pytorch 2.1.10+gitcd132db   # pinned
- torch                       2.1.0a0+git4de5871  # pytorch branch: dev/triton-test-3.0

`test-triton.sh --skip-deps` pass

**Comment by AshburnLee** [comment]
I think we may need a doc on how to use this script for users.

To be honest, I'm confused reading this script :sweat_smile: , the `--help` dose not help at all "Example usage: ./compile-pytorch-ipex.sh [--pytorch | --upstream-pytorch | --ipex | --no-op-ipex | --pinned | --source | --clean | --venv]". This can't show me how to use the script.

Without the instruction I can only think of the 4 use cases as commented above. I'm not sure if they are REAL use cases.

Please correct me if I was wrong, thanks.

Since this script has been constantly changes over an extended period, I am considering to refactor it for friendly readability.

**Comment by AshburnLee** [comment]
Append another use case:
Case  1 + `--clean`:
`./scripts/compile-pytorch-ipex.sh --upstream-pytorch --clean`
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+git3515090  # upstream pytorch commit (https://github.com/pytorch/pytorch/pull/134457)
`test-triton.sh --skip-deps` pass

**Comment by Retribution98** [comment]
@AshburnLee 
> Build upstream pytorch with branch dev/triton-test-3.0

What is this? I don't see this branch in the upstream.
As far as I can tell from this script, this branch is used with https://github.com/Stonepia/pytorch and is based on torch 2.1.0a0.
It looks like it should be used with IPEX. 

> ./scripts/compile-pytorch-ipex.sh --upstream-pytorch (--no-op-ipex --source)
Why do you use '(' and ')' ?

File: scripts/test-triton.sh [hunk 7]
```diff
@@ -122,7 +122,7 @@ if [ "$TRITON_TEST_REPORTS" == true ]; then
     capture_runtime_env
 fi
 
-$SKIP_DEPS || $SCRIPTS_DIR/compile-pytorch-ipex.sh --pinned $ARGS
```
Comment (anmyachev) [inline scripts/test-triton.sh:125]: @Retribution98 I believe we can remove `ARGS` from this script at all.

Comment (Retribution98) [reply scripts/test-triton.sh:125]: It is declared in all scripts, even if it is not used. I think we should have the same structure in different places. That seems like a separate issue, doesn't it?

Comment (anmyachev) [reply scripts/test-triton.sh:125]: If we leave it as is, the parameters will get into this variable without any messages/warnings or processing. Avoiding such a situation seems more important to me personally than having the same interface everywhere.

**Review by vlad-penkin — APPROVED** [review]
LGTM

**Comment by AshburnLee** [comment]
After swiching to newer PTDB(0.5.2->**0.5.3**) and Agama(914.32->**950.13**), `test-triton.sh` works fine for upstream-pytorch both from source & from pinned:

./scripts/compile-pytorch-ipex.sh --upstream-pytorch  # default is pinned
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+gitb7baa06   # pinned upstream pytorch

./scripts/compile-pytorch-ipex.sh --upstream-pytorch --source
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+gitf33bcbe   # source upstream pytorch

@Retribution98 @vlad-penkin
