### PR TITLE
Fix Flex Attn UT failures

### LINKED ISSUE #5129: Flex Attn starts to fail after 92eb442262f4bbc8acf37c3831c644395e178b2f
CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/17794152919

Summary:
```bash
The following tests failed consistently: ['test/inductor/test_flex_attention.py::TestFlexAttentionXPU::test_differentiable_logsumexp_compiled_xpu', 'test/inductor/test_flex_attention.py::TestFlexAttentionXPU::test_multiple_mask_calls_xpu', 'test/inductor/test_flex_attention.py::TestFlexAttentionXPU::test_selective_ac_ops_to_save0_xpu', 'test/inductor/test_flex_attention.py::TestFlexAttentionXPU::test_selective_ac_ops_to_save1_xpu', 'test/inductor/test_flex_attention.py::TestFlexAttentionXPU::test_selective_ac_ops_to_save2_xpu']
```

92eb442262f4bbc8acf37c3831c644395e178b2f

@whitneywhtsang please take a look

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Before 92eb442262f4bbc8acf37c3831c644395e178b2f, `getStride(ptr, 0)` would be 1 for column major, i.e, pitch would be smaller than 64 bytes (HW restriction), so `getPitch` would return `nullptr`, and 2d block load would not be generated. This PR goes back to the original behavior and early return for column major.

Flex Attn UT: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/17833144533/job/50703282622 (GOOD)
Flex Attn benchmark: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/17836148975/job/50713713366 (GOOD)

Fixes #5129

### CODE REVIEW

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp [hunk 1]
```diff
@@ -2240,13 +2239,15 @@ struct LoadOpToBlockIOConversion
       break;
     }
 
+    assert(memoryRowMajor || !getPitch(rewriter, ptr, elemSizeInBits, 0) &&
+                                 "Ensure column major was never supported");
```
Comment (whitneywhtsang) [inline third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp]: Remove after testing
```suggestion
```

**Review by anmyachev — APPROVED** [review]
