### PR TITLE
[DRIVER][VLLM] Auto-retry kernel compilation with large GRF mode on build failure

### LINKED ISSUE #3777: [VLLM] RuntimeError: Triton Error [ZE]: 0x78000011 happens on Ubuntu22.04
### Describe the bug

Error:
```
ERROR 03-27 11:38:51 [core.py:343]   File "/workspace/vllm-13/vllm/v1/sample/rejection_sampler.py", line 194, in rejection_sample
ERROR 03-27 11:38:51 [core.py:343]     recovered_token_ids = sample_recovered_tokens(
ERROR 03-27 11:38:51 [core.py:343]   File "/workspace/vllm-13/vllm/v1/sample/rejection_sampler.py", line 406, in sample_recovered_tokens
ERROR 03-27 11:38:51 [core.py:343]     sample_recovered_tokens_kernel[(batch_size, max_spec_len)](
ERROR 03-27 11:38:51 [core.py:343]   File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 336, in <lambda>
ERROR 03-27 11:38:51 [core.py:343]     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
ERROR 03-27 11:38:51 [core.py:343]   File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 585, in run
ERROR 03-27 11:38:51 [core.py:343]     kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata,
ERROR 03-27 11:38:51 [core.py:343]   File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 417, in __getattribute__
ERROR 03-27 11:38:51 [core.py:343]     self._init_handles()
ERROR 03-27 11:38:51 [core.py:343]   File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 412, in _init_handles
ERROR 03-27 11:38:51 [core.py:343]     self.module, self.function, self.n_regs, self.n_spills = driver.active.utils.load_binary(
ERROR 03-27 11:38:51 [core.py:343]   File "/usr/local/lib/python3.10/dist-packages/triton/backends/intel/driver.py", line 209, in load_binary
ERROR 03-27 11:38:51 [core.py:343]     return self.shared_library.load_binary(args)
ERROR 03-27 11:38:51 [core.py:343] RuntimeError: Triton Error [ZE]: 0x78000011
ERROR 03-27 11:38:51 [core.py:343]

```

This load library step is successful in my unit test and only fails during runtime which should have big tensors.  Is there any way to determine how much memory will triton kernel launch needs? 

### Environment details

Environment:
```
base image:  intel/deep-learning-essentials:2025.0.2-0-devel-ubuntu22.04
hardware: PVC 1100
driver version: 

libze-dev/now 1.19.2.0-1077~22.04 amd64 [installed,local]
libze-intel-gpu-dev/now 24.52.32224.14-1077~22.04 amd64 [installed,local]
libze-intel-gpu1/now 24.52.32224.14-1077~22.04 amd64 [installed,local]
libze1/now 1.19.2.0-1077~22.04 amd64 [installed,local]

IPEX:
torch==2.7.0+xpu
torchaudio
torchvision
pytorch-triton-xpu
--extra-index-url=https://download.pytorch.org/whl/test/xpu
intel_extension_for_pytorch  2.7
oneccl_bind_pt-2.7.0+xpu-cp310-cp310-linux_x86_64
```

### PR DESCRIPTION
**Pull request by Egor-Krivov**
## Problem

When a Triton kernel requires too many registers on Intel XPU, the IGC backend
compiler fails with "total scratch space exceeds HW supported limit" (PTSS).
The existing retry logic in `load_binary()` only handles the case where
compilation **succeeds** but has a high spill count (>1000). When compilation
**fails entirely**, the error propagates immediately without attempting large
GRF mode.

Users must manually add `grf_mode='256'` to work around this, which is not
discoverable and differs from NVIDIA where such issues don't occur.

Fixes #3777

## Solution

Extend the GRF retry logic in `load_binary()` (driver.c) to also cover
complete build failures:

- When `zeModuleCreate` fails with `ZE_RESULT_ERROR_MODULE_BUILD_FAILURE`
  and no GRF mode was explicitly set, clear the error and retry compilation
  with `-cl-intel-256-GRF-per-thread`
- If the retry succeeds, continue with the large-GRF kernel
- If the retry also fails, propagate the original error
- Print a recovery message to stderr so the user knows the initial error
  was handled
- Apply the same retry-on-failure pattern to the `ocloc` offline compilation
  path in `make_zebin()` (compiler.py)

The existing spill-count-based retry (successful compilation but >1000 spills)
is unchanged and still applies when the build-failure retry is not triggered.

## Testing

Added parametrized test `test_auto_grf_on_build_failure` covering:
- `grf_mode='default'`: build fails → auto-retries with large GRF → succeeds
- `grf_mode='256'`: explicit large GRF → compiles directly, no retry
- `grf_mode='128'`: explicit small GRF → fails, no retry (respects user choice)

When I run the original reproducer from #3777  I now get a pass:

```
(triton) (312) jovyan@jupyter-ekrivov:~/triton/intel-xpu-backend-for-triton/issues/3777/ut$ python test_old.py 
L0 build module failed. Log: 
warning: [RetryManager] Start recompilation of the kernel
in kernel: 'sample_recovered_tokens_kernel'

error: total scratch space exceeds HW supported limit for kernel sample_recovered_tokens_kernel: 270848 bytes (max permitted PTSS 262144 bytes)
error: backend compiler failed build.

(I): Build failure recovered by retrying with large GRF mode for "sample_recovered_tokens_kernel"
```

### CODE REVIEW

File: third_party/intel/backend/driver.c [hunk 1]
```diff
@@ -272,12 +272,46 @@ extern "C" EXPORT_FUNC PyObject *load_binary(PyObject *args) {
...
+      return NULL;
+    }
+
+    l0_module = l0_module_retry;
+    l0_kernel = l0_kernel_retry;
+    n_spills = n_spills_retry;
+
+    // Always print recovery message to stderr to follow up on the
+    // "L0 build module failed" error that was already printed.
+    std::cerr << "(I): Build failure recovered by retrying with large GRF "
```
Comment (Egor-Krivov) [inline third_party/intel/backend/driver.c:313]: I write to stderr because stderr at this point already contains error message from IGC and we need to tell the user that issue is probably fixed

File: python/test/unit/intel/test_driver.py [hunk 2]
```diff
@@ -99,3 +99,51 @@ def test_has_opencl_extension_error(device):
...
     with pytest.raises(RuntimeError, match="Device is not found"):
         driver.active.utils.has_opencl_extension(device_count, b"cl_khr_fp16")
+
+
+@pytest.mark.parametrize("grf_mode, expect_retry, expect_fail",
+                         [("default", True, False),  # Should auto-retry with large GRF and succeed
+                          ("256", False, False),  # Explicit large GRF — compiles on first attempt
+                          ("128", False, True),  # Explicit small GRF — should fail, no retry
+                          ])
+def test_auto_grf_on_build_failure(device, monkeypatch, capfd, grf_mode, expect_retry, expect_fail):
```
Comment (anmyachev) [inline python/test/unit/intel/test_driver.py]: Let's test both: `make_zebin` and `load_binary`. I guess `TRITON_XPU_GEN_NATIVE_CODE` should help for this.

File: third_party/intel/backend/driver.c [hunk 3]
```diff
@@ -272,12 +272,46 @@ extern "C" EXPORT_FUNC PyObject *load_binary(PyObject *args) {
...
+                << "\", retrying with large GRF mode" << std::endl;
+
+    PyErr_Clear();
+    build_flags.addLargeGRFSizeFlag();
+
+    auto [l0_module_retry, l0_kernel_retry, n_spills_retry] =
+        compileLevelZeroObjects(binary_ptr, binary_size, kernel_name, l0_device,
+                                l0_context, build_flags(), is_spv);
+    if (PyErr_Occurred()) {
+      // Retry also failed — propagate the error.
```
Comment (anmyachev) [inline third_party/intel/backend/driver.c]: Should we raise the initial exception here to be align with `make_zebin`?

**Comment by Egor-Krivov** [comment]
@anmyachev I updated the PR based on your feedback, but GH doesn't show changes for some reason
https://github.com/intel/intel-xpu-backend-for-triton/compare/main...egor/issue_3777

**Comment by Egor-Krivov** [comment]
Ok, after https://github.com/intel/intel-xpu-backend-for-triton/pull/6123/commits/36ab67d91544700c3908604cdf00347bff8c161a PR got updated.

File: third_party/intel/backend/driver.c [hunk 4]
```diff
@@ -272,12 +272,56 @@ extern "C" EXPORT_FUNC PyObject *load_binary(PyObject *args) {
...
+                << "\", retrying with large GRF mode" << std::endl;
+
+    build_flags.addLargeGRFSizeFlag();
+
+    auto [l0_module_retry, l0_kernel_retry, n_spills_retry] =
+        compileLevelZeroObjects(binary_ptr, binary_size, kernel_name, l0_device,
+                                l0_context, build_flags(), is_spv);
+    if (PyErr_Occurred()) {
+      // Retry also failed — restore and propagate the original error.
+      PyErr_Clear();
```
Comment (anmyachev) [inline third_party/intel/backend/driver.c]: I guess we don't need to use `PyErr_Clear();`.
`Set the error indicator from the three objects, type, value, and traceback, clearing the existing exception if one is set.` according to https://docs.python.org/3.14/c-api/exceptions.html#c.PyErr_Restore.

Comment (Egor-Krivov) [reply third_party/intel/backend/driver.c]: Done

**Comment by jikunshang** [comment]
may I know which triton-xpu release will contain this fix?
