### PR TITLE
[triton-raise-block-ptr]: Fix failing test 

### LINKED ISSUE #3218: [TRITON-BP]: Failure on `tt.addptr` due to unhandled `arith.extsi` operation
```
TritonRaiseBlockPointer: encountered addptr operand produced by an unsupported operation
0x562a089e0940
/home/jovyan/tmp/test1.mlir:12:8: remark: TritonRaiseToBlockPointer: Failed to rewrite AddPtrOp
  %5 = tt.addptr %0, %4 : tensor<16x16x!tt.ptr<f16>>, tensor<16x16xi64>
```

Test case:
```
tt.func public @test_masked_store(%arg0: !tt.ptr<f16>) {
  %cst = arith.constant dense<0> : tensor<16x1xi64>
  %cst_0 = arith.constant dense<1.500000e+01> : tensor<16x16xf16>
  %0 = tt.splat %arg0 : !tt.ptr<f16> -> tensor<16x16x!tt.ptr<f16>>
  %1 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
  %2 = arith.extsi %1 : tensor<16xi32> to tensor<16xi64>
  %3 = tt.expand_dims %2 {axis = 1 : i32} : tensor<16xi64> -> tensor<16x1xi64>
  %4 = tt.broadcast %3 : tensor<16x1xi64> -> tensor<16x16xi64>
  %5 = tt.addptr %0, %4 : tensor<16x16x!tt.ptr<f16>>, tensor<16x16xi64>  // ERROR
  %6 = arith.cmpi sge, %3, %cst : tensor<16x1xi64>
  %7 = tt.broadcast %6 : tensor<16x1xi1> -> tensor<16x16xi1>
  // TODO: Replace above with below once support for masked stores is complete.
  //  tt.store %5, %cst_0, %7 : tensor<16x16x!tt.ptr<f16>>
  tt.store %5, %cst_0 : tensor<16x16x!tt.ptr<f16>>
  tt.return
}
```

### PR DESCRIPTION
**Pull request by etiotto**
Fixes #3218

### CODE REVIEW

**Comment by etiotto** [comment]
Depends on https://github.com/intel/intel-xpu-backend-for-triton/pull/3198

File: third_party/intel/lib/TritonRaiseBlockPointer/TritonRaiseBlockPointer.cpp [hunk 1]
```diff
@@ -1095,6 +1103,28 @@ LogicalResult TritonRaiseBlockPointer::visitAddPointerOperand(
...
+
+template <>
+LogicalResult TritonRaiseBlockPointer::visitAddPointerOperand(
+    arith::ExtSIOp remOp, PtrState &state, Location loc, OpBuilder &builder) {
+  return visitAddPointerExtOperand(remOp, state, loc, builder);
+}
+
+template <>
+LogicalResult TritonRaiseBlockPointer::visitAddPointerOperand(
+    arith::ExtUIOp remOp, PtrState &state, Location loc, OpBuilder &builder) {
```
Comment (mfrancepillois) [inline third_party/intel/lib/TritonRaiseBlockPointer/TritonRaiseBlockPointer.cpp:1124]: same
```suggestion
    arith::ExtUIOp extOp, PtrState &state, Location loc, OpBuilder &builder) {
```

**Review by mfrancepillois — APPROVED** [review]
LGTM, just some nits.
A general comment: I'm not sure that the name of the function `visitAddPointerOperand` is really representative of what this function does, as many operations which are not `addOp` are visited by this function.

File: third_party/intel/lib/TritonRaiseBlockPointer/TritonRaiseBlockPointer.cpp [hunk 2]
```diff
@@ -1095,6 +1103,28 @@ LogicalResult TritonRaiseBlockPointer::visitAddPointerOperand(
...
+        llvm::is_one_of<OpTy, arith::ExtSIOp, arith::ExtUIOp>::value, bool>>
+LogicalResult TritonRaiseBlockPointer::visitAddPointerExtOperand(
+    OpTy extOp, PtrState &state, Location loc, OpBuilder &builder) {
+  assert(state.isEmpty() && "state is a return argument");
+  return visitOperand(extOp.getIn(), state, loc, builder);
+}
+
+template <>
+LogicalResult TritonRaiseBlockPointer::visitAddPointerOperand(
+    arith::ExtSIOp remOp, PtrState &state, Location loc, OpBuilder &builder) {
```
[the remark this answers is not in the document]
Comment (etiotto) [reply third_party/intel/lib/TritonRaiseBlockPointer/TritonRaiseBlockPointer.cpp]: done

File: third_party/intel/lib/TritonRaiseBlockPointer/TritonRaiseBlockPointer.cpp (hunk 1 above)
Comment (etiotto) [reply third_party/intel/lib/TritonRaiseBlockPointer/TritonRaiseBlockPointer.cpp:1124]: done
