### PR TITLE
[LoadStoreConversion] Handle negative indices in boundary checks

### LINKED ISSUE #3240: FAILED `language/test_block_pointer.py::test_block_copy` on BMG

### PR DESCRIPTION
**Pull request by dchigarev**
Fixes #3240

The issue appeared after disabling [`RewriteTensorPointerPass`](https://github.com/intel/intel-xpu-backend-for-triton/blob/8b1aee9d0f8b82d719162e0a001860bbbc3bd184/third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp#L284) in [this PR](https://github.com/intel/intel-xpu-backend-for-triton/pull/2584) (#2584). The disabled pass was responsible for the [creation of boundary-check-masks](https://github.com/intel/intel-xpu-backend-for-triton/blob/8b1aee9d0f8b82d719162e0a001860bbbc3bd184/third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp#L195) and checked that [the offset index is greater that zero](https://github.com/intel/intel-xpu-backend-for-triton/blob/8b1aee9d0f8b82d719162e0a001860bbbc3bd184/third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp#L207-L213) avoiding out-of-bound loads/stores in case of a negative pointer offsets (exactly the case we see in [the problematic test](https://github.com/intel/intel-xpu-backend-for-triton/blob/8b1aee9d0f8b82d719162e0a001860bbbc3bd184/python/test/unit/language/test_block_pointer.py#L14-L15)). The [`LoadStoreConversion`](https://github.com/intel/intel-xpu-backend-for-triton/blob/main/third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp#L164) that was supposed to "replace" the disabled pass in terms of boundary checks, [doesn't have "index >= 0" check](https://github.com/intel/intel-xpu-backend-for-triton/blob/main/third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp#L164), causing invalid reads/writes in case of negative indices.

We don't see any issues in PVC's CI since the driver doesn't seem to report segfaults to sycl, causing them to be ignored. But on our testing BMG machine, the driver blocks all following commands to the GPU after a segfault, causing the test to fail.

The test (`language/test_block_pointer.py::test_block_copy`) passes on the test BMG machine after this fix.

### CODE REVIEW

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp [hunk 1]
```diff
@@ -263,8 +263,11 @@ struct LoadStoreConversionBase {
             {blockPtr.begin() + blockShape, blockPtr.begin() + blockStride},
             b.int_val(1, 1),
             [&](const Value &index, const Value &shape, const Value &mask) {
-              // mask = mask && (index < shape)
-              return b.and_(b.icmp_slt(index, b.trunc(i32_ty, shape)), mask);
+              // mask = mask && (index < shape) && idx > 0
```
Comment (dchigarev) [inline third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp:266]:
```suggestion
              // mask = mask && (index < shape) && idx >= 0
```

**Review by whitneywhtsang — APPROVED** [review]
