### PR TITLE
Fix AxisInfo handling of PoisonOp producing MemDesc (#8489)

### LINKED ISSUE #5464: Reland upstream commit `4734af3`
Reland 4734af313ba2657f7ec8bd33ae5d5fe9249ab62e that is temporarily reverted in https://github.com/intel/intel-xpu-backend-for-triton/pull/5460 by f1e5aadaca84fa42a07d4d64f7981b07c63b0957.

CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/19287863486/job/55152692885

### PR DESCRIPTION
**Pull request by wdziurdz**
The PoisonOpAxisInfoVisitor incorrectly returns rank=1 for ub.poison operations producing pointer-to-tensor types like !tt.ptr<tensor<128x64xf16>>. This wrong rank propagates through unrealized_conversion_cast operations created during lowering, causing assertion failures in AxisInfo::join().

Fixes #5464

### CODE REVIEW

**Comment by wdziurdz** [comment]
@etiotto @whitneywhtsang pls look on this.

File: third_party/intel/lib/Analysis/AxisInfo.cpp [hunk 1]
```diff
@@ -295,16 +295,18 @@ class PoisonOpAxisInfoVisitor final : public AxisInfoVisitorImpl<ub::PoisonOp> {
...
+      rank = shape.getRank();
+    } else if (auto ptrTy = dyn_cast<PointerType>(op.getType())) {
+      if (auto tensorType = dyn_cast<RankedTensorType>(ptrTy.getPointeeType()))
+        rank = tensorType.getRank();
     }
 
-    return AxisInfo(/*contiguity=*/{1}, /*divisibility=*/{largePowerOf2},
-                    /*constancy=*/{1});
+    // Poison values are never accessed, thus assume optimistic values.
+    return AxisInfo(AxisInfo::DimVectorT(rank, largePowerOf2),
```
Comment (anmyachev) [inline third_party/intel/lib/Analysis/AxisInfo.cpp]: why `shape.getShape()` isn't used anymore?

File: lib/Analysis/AxisInfo.cpp [hunk 2]
```diff
@@ -276,8 +276,12 @@ class PoisonOpAxisInfoVisitor final : public AxisInfoVisitorImpl<ub::PoisonOp> {
   getAxisInfo(ub::PoisonOp op,
               ArrayRef<const dataflow::Lattice<AxisInfo> *> operands) override {
     unsigned rank = 1;
-    if (auto shape = dyn_cast<mlir::ShapedType>(op.getType()))
+    if (auto shape = dyn_cast<RankedTensorType>(op.getType())) {
       rank = shape.getRank();
+    } else if (auto ptrTy = dyn_cast<PointerType>(op.getType())) {
```
Comment (anmyachev) [inline lib/Analysis/AxisInfo.cpp:281]: Why do we need a separate branch?

File: third_party/intel/lib/Analysis/AxisInfo.cpp (hunk 1 above)
Comment (wdziurdz) [reply third_party/intel/lib/Analysis/AxisInfo.cpp]: Changes reverted.

File: lib/Analysis/AxisInfo.cpp (hunk 2 above)
Comment (wdziurdz) [reply lib/Analysis/AxisInfo.cpp:281]: PR upstream: https://github.com/triton-lang/triton/pull/8824. Summarize wrong rank for %0 = ub.poison : !tt.ptr<tensor<128x64xf16, ...>>

**Comment by wdziurdz** [comment]
> Can you upstream this fix to the OpenAI repo?
PR upstream: https://github.com/triton-lang/triton/pull/8824

**Comment by etiotto** [comment]
Upstream PR was rejected, We will need to maintain the fix downstream untill we do not rely on block pointers support any longer.

File: test/TritonGPU/pipeline-assign-latencies.mlir [hunk 3]
```diff
@@ -1149,7 +1149,23 @@ module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.targ
 }
 
 // -----
+// Test that ub.poison producing a memdesc does not get treated like a tensor
```
Comment (etiotto) [inline test/TritonGPU/pipeline-assign-latencies.mlir:1152]: Can you move this tests into the intel specific tests, and use a different layout other than "nvmma_shared"

Comment (wdziurdz) [reply test/TritonGPU/pipeline-assign-latencies.mlir:1152]: @etiotto  you added a comment to the original LIT test (from the reland commit). I moved my LIT test to the Intel-specific one (without nvmma_shared). Done

**Review by etiotto — APPROVED** [review]
