### PR TITLE
[LoadOpToBlockIOConversion] Limit `vBlocks` of 2d block load

### LINKED ISSUE #5308: `test/inductor/test_flex_attention.py::TestFlexAttentionXPU::test_seq_masking_xpu_float16` is broken
CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/18493060126/job/52690986128

To reproduce: `python test/inductor/test_flex_attention.py TestFlexAttentionXPU.test_seq_masking_xpu_float16`

Error:
```bash
L0 build module failed. Log: 
error: undefined reference to `__internal_intel_sub_group_2d_block_read_8b_1r16x4c_cache_controls'
in function: '__internal_intel_sub_group_2d_block_read_8b_1r16x4c_cache_controls' called by kernel: 'triton_tem_fused_0'

error: backend compiler failed build.

Error during Intel loadBinary: ZE_RESULT_ERROR_MODULE_BUILD_FAILURE
```

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Fixes #5308

Flex Attn UT CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/18510656080 (GOOD)

### CODE REVIEW

**Review by chengjunlu — APPROVED** [review]

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp [hunk 1]
```diff
@@ -2500,6 +2500,10 @@ struct LoadOpToBlockIOConversion
                        static_cast<int>(MAX_WIDTH / totalBytesPerRowPerMatrix));
     // vBlocks has HW limitation of 4.
     vBlocks = std::min(vBlocks, 4);
+    // Limit vBlocks to 1 if block size is smaller than GRF size.
+    const unsigned GRF_SIZE = 64;
+    if (tileHeight * tileWidth * packedElemSizeInBits / 8 < GRF_SIZE)
```
Comment (chengjunlu) [inline third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp:2505]: This fix this issue https://github.com/intel/intel-xpu-backend-for-triton/issues/5243 as well.
