### PR TITLE
[CI][sglang] Fixed sglang testing, added pin, updated patch

### LINKED ISSUE #5375: [CI][sglang] Our sglang build is broken
Reason:
our git patch is outdated

Example:
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/18628950913/job/53110930563

### PR DESCRIPTION
**Pull request by Egor-Krivov**
1. Adds sglang pin
2. Updates patch, current patch is broken
3. Unifies sglang testing with the rest of third-party testing

Closes #5375

### CODE REVIEW

File: scripts/test-triton.sh [hunk 1]
```diff
@@ -672,7 +693,7 @@ run_vllm_tests() {
 
 run_triton_kernels_tests() {
   echo "***************************************************"
-  echo "******    Running Triton Kernels tests      ******"
+  echo "******    Running Triton Kernels tests      ******"requirements.txpt
```
Comment (whitneywhtsang) [inline scripts/test-triton.sh]:
```suggestion
  echo "******    Running Triton Kernels tests      ******"
```
