### PR TITLE
[LoadStoreOpToLLVM] Conditionally pre-apply alignment in descriptor load lowering

### LINKED ISSUE #6571: [vLLM] Unified attention tensor descriptor performance regression (bf16 and fp8)
Grafana dashboard: https://benchmarks.glados.intel.com/d/VdsWtYwNz/third-party-benchmarks?orgId=1&var-tablename=triton_third_party_benchmarks_view&var-tag=ci&var-bench_group=vllm&var-bench=unified-attn-bf16&var-bench=unified-attn-fp8&var-compiler=All&var-value_name=All&var-device=Max%201550&from=1774936800000&to=now

Currently bisecting the issue (first bad to last good):
```
* ef03366a9d [Analysis] Remove block pointer handling from AxisInfoExt and StrideInfo (#6551)
* e20ff5f7d8 Support PAD_NAN for tensor descriptor block IO loads (#6548)
* 66ab5a922c [TEST] Convert fp4tofp.mlir from block pointers to tensor descriptors (#6547)
* 706d56289f [vLLM] Add vLLM build dir to gitignore (#6521)
* 00a6492e3c Merge OpenAI Triton commit `326fc86` (#6539)
* 665d0d5d1d [TEST][PROTON] Make test_multi_stream device-agnostic for XPU (#6544)
* e9ddc1db8c Merge OpenAI Triton commit `6cb8445` (#6542)
* f061e871de Enable `sanitize overflow` (#6533)
* cf5f65e4f5 [github-bot] Update spirv-llvm-translator.conf (#6537)
* eaf2e2e538 [LoadStoreOpToLLVM] Pre-apply alignment in descriptor load lowering (#6538)
* 6b4c763782 Update PyTorch pin (#6515)
* a9c98df5b5 Remove `TensorDescToBlockPointer` (#6484)
* 39bc62288a [TEST][PROTON] Enable test_clear_data on XPU (#5754) (#6527)
```

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Only pre-apply 64-byte alignment compensation when the column descriptor index is non-zero. When the column index is a known constant zero (e.g., unified attention K/V cache loads), skip the pre-alignment to preserve the natural expression tree that LLVM optimizes to match the block pointer lowering path.

Fixes #6571

### CODE REVIEW

**Review by chengjunlu — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
[Grafana](https://benchmarks.glados.intel.com/d/1pXX4hUSz/microbenchmarks?orgId=1&var-tag=ci&var-tag=client&var-tag=pr-6655&var-bench=All&var-device=Max%201550&var-device=B580&var-compiler=triton&var-backend=All&var-table_old=ci&var-baseline_backend_old=triton-ci-Max%201550&var-target_backend_old=triton-ci-Max%201550&var-okr_device_old=All) no regressions.

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp [hunk 1]
```diff
@@ -2595,16 +2595,19 @@ struct DescriptorLoadOpToBlockIOConversion
...
+    // this, LLVM's CSE factors out (descIndex + delta) as a common
+    // subexpression shared across different operand loads, producing a
     // suboptimal instruction schedule.
-    constexpr int64_t ALIGNMENT_MASK = 0x3f;
     unsigned descBlockColIdx =
         mapResultDimToDescDim(isTransposeRequired ? rowDim : colDim);
-    {
+    auto descColConst = mlir::triton::intel::getFoldedConstantValue(
+        descIndices[descBlockColIdx]);
+    if (!descColConst || *descColConst != 0) {
```
Comment (etiotto) [inline third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp:2609]: Nit: per the project's symmetric `auto` rule, `getFoldedConstantValue()` is a regular function call whose return type (`std::optional<int64_t>`) is not obvious from the name. Consider spelling it out:

```cpp
std::optional<int64_t> descColConst = mlir::triton::intel::getFoldedConstantValue(
    descIndices[descBlockColIdx]);
```

**Review by etiotto — COMMENTED** [review]
Clean fix for the unified attention regression. Only one minor style nit.

File: third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp (hunk 1 above)
Comment (whitneywhtsang) [reply third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp:2609]: Done in #6663
