### PR TITLE
[SCRIPTS] Fix Liger install replacing XPU torch via compressed-tensors pin

### LINKED ISSUE #6602: [Third party benchmarks] All benchmarks fail: "Torch not compiled with XPU enabled"
```
Traceback (most recent call last):
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/python/test/microbenchmark/launch_overhead.py", line 120, in <module>
    main(use_tensor_desc=False, reports_dir=args.reports)
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/python/test/microbenchmark/launch_overhead.py", line 89, in main
    targs = [torch.zeros(1, device="xpu") for _ in range(5)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.12.7/lib/python3.12/site-packages/torch/xpu/__init__.py", line 136, in _lazy_init
    raise AssertionError("Torch not compiled with XPU enabled")
AssertionError: Torch not compiled with XPU enabled
```

Bisected the failures to 1a2ed06f58b5c97097ef52974e10c61a95c61768.

Good run: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/24074470123
Bad run: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/24146019587

### PR DESCRIPTION
**Pull request by wdziurdz**
The fix pins torch/triton to their current versions via a constraints file so pip can't downgrade/replace them.

Fixes #6602

### CODE REVIEW

File: scripts/test-triton.sh [hunk 1]
```diff
@@ -793,6 +793,21 @@ run_test_deps_install() {
   pip install pytest pytest-cov pytest-xdist
 }
 
+# pip install that pins torch/triton to currently installed versions via constraints.
+# Prevents transitive deps from pulling in PyPI torch/triton.
+guarded_pip_install() {
+  local constraints
+  constraints=$(mktemp)
+  python -c "
+import torch; print(f'torch=={torch.__version__}')
```
Comment (quinnlp) [inline scripts/test-triton.sh]: Should we guard the `torch` import with `try` like you did for `triton`?

**Review by quinnlp — APPROVED** [review]
LGTM waiting on https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/24189977060/job/70604322913

File: scripts/test-triton.sh
Comment (anmyachev) [inline scripts/test-triton.sh:824]: Here we are solving the problem of reinstalling dependencies, why did this stop working?

**Review by anmyachev — CHANGES_REQUESTED** [review]

File: scripts/test-triton.sh
Comment (wdziurdz) [reply scripts/test-triton.sh:824]: You right this is work I changed fix and minimize.

File: scripts/test-triton.sh [hunk 2]
```diff
@@ -856,7 +856,7 @@ run_liger_install() {
   if ! pip list | grep "liger_kernel" ; then
     # Liger requires transformers<5.0
     # https://github.com/linkedin/Liger-Kernel/issues/978
-    pip install 'transformers<5.0' 'pandas<3.0' datasets -e Liger-Kernel
+    pip install 'compressed-tensors<0.15' 'transformers<5.0' 'pandas<3.0' datasets -e Liger-Kernel
```
Comment (anmyachev) [inline scripts/test-triton.sh:859]: so, why it helps?

**Comment by anmyachev** [comment]
@wdziurdz please also change the title and description of the pull request.

File: scripts/test-triton.sh (hunk 2 above)
Comment (wdziurdz) [reply scripts/test-triton.sh:859]: @anmyachev  here explain : https://github.com/intel/intel-xpu-backend-for-triton/issues/6602#issuecomment-4222144521. Shortly compressed-tensors==0.15 introduce this constrain torch < 3.11  than pip replaced XPU torch with PyPI torch and than benchmarks broke no xpu device

Comment (anmyachev) [reply scripts/test-triton.sh:859]: I see, thanks

**Review by anmyachev — APPROVED** [review]
