### PR TITLE
Fix for crash in ScfPattern::matchAndRewrite

### LINKED ISSUE #1622: [AdvancedPath]: Crash in `ScfPattern::matchAndRewrite`
Given the following test case: 
```
tt.func public @simplify_scf_for(%arg0: tensor<16x8xf16>, %arg1: tensor<16x8xf16>, %arg2: !tt.ptr<f16, 1>,
                                 %arg3: i64, %arg4: i64, %arg5: i64, %arg6: i32, %arg7: i32) {
  // CHECK-LABEL: @simplify_scf_for
  // CHECK:      [[GLUE:%.*]] = triton_intel_gpu.glue
  // CHECK-NEXT: [[RES:%.*]] = scf.for {{.*}} iter_args([[INIT1:%.*]] = [[GLUE]]) -> (tensor<16x16xf16>) : i32 {
  // CHECK:        scf.yield {{.*}} : tensor<16x16xf16>
  // CHECK-NEXT: }
  // CHECK-NEXT: [[PTR:%.*]] = tt.make_tensor_ptr %arg2
  // CHECK-NEXT: tt.store [[PTR]], [[RES]]
  %lb = arith.constant 0 : i32
  %ub = arith.constant 32 : i32
  %st = arith.constant 1 : i32
  %c1_i64 = arith.constant 1 : i64
  %glue = triton_intel_gpu.glue %arg0, %arg1 : (tensor<16x8xf16>, tensor<16x8xf16>) -> tensor<16x16xf16>
  %res = scf.for %iv = %lb to %ub step %st iter_args(%arg = %glue) -> (tensor<16x16xf16>) : i32 {
    %e1 = triton_intel_gpu.extract %arg[0] : tensor<16x16xf16> -> tensor<16x8xf16>
    %e2 = triton_intel_gpu.extract %arg[1] : tensor<16x16xf16> -> tensor<16x8xf16>
    %g1 = triton_intel_gpu.glue %e1, %e2 : (tensor<16x8xf16>, tensor<16x8xf16>) -> tensor<16x16xf16>
    scf.yield %g1 : tensor<16x16xf16>
  }
  %ptr = tt.make_tensor_ptr %arg2, [%arg3, %arg4], [%arg5, %c1_i64], [%arg6, %arg7] {order = array<i32: 1, 0>} : <tensor<16x16xf16>>
  tt.store %ptr, %res {boundaryCheck = array<i32: 0, 1>, cache = 1 : i32, evict = 1 : i32} : !tt.ptr<tensor<16x16xf16>>
  tt.return
}
```
The compiler (with PR #1540) crashes with the following back trace:
```
triton-opt: /home/runner/work/triton/triton/llvm-project/mlir/lib/IR/PatternMatch.cpp:162: virtual void mlir::RewriterBase::eraseOp(mlir::Operation *): Assertion `op->use_empty() && "expected 'op' to have no uses"' failed. PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace. Stack dump: 0. Program arguments: /home/jovyan/intel-xpu-backend-for-triton/python/build/cmake.linux-x86_64-cpython-3.10/bin/triton-opt /home/jovyan/intel-xpu-backend-for-triton/test/TritonIntelGPU/match-target-size.mlir -split-input-file -tritonintelgpu-match-target-size #0 0x0000562ff12855f7 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/jovyan/intel-xpu-backend-for-triton/python/build/cmake.linux-x86_64-cpython-3.10/bin/triton-opt+0x2f055f7) #1 0x0000562ff128311e llvm::sys::RunSignalHandlers() (/home/jovyan/intel-xpu-backend-for-triton/python/build/cmake.linux-x86_64-cpython-3.10/bin/triton-opt+0x2f0311e) #2 0x0000562ff1285caf SignalHandler(int) Signals.cpp:0:0 #3 0x00007fda20995520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520) #4 0x00007fda209e99fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc) #5 0x00007fda20995476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476) #6 0x00007fda2097b7f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3) #7 0x00007fda2097b71b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b) #8 0x00007fda2098ce96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96) #9 0x0000562ff11e474e (/home/jovyan/intel-xpu-backend-for-triton/python/build/cmake.linux-x86_64-cpython-3.10/bin/triton-opt+0x2e6474e) #10 0x0000562feebad90e (anonymous namespace)::ScfPattern::matchAndRewrite(mlir::scf::ForOp, mlir::PatternRewriter&) const /home/jovyan/intel-xpu-backend-for-triton/third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp:393:19 ...
```

### PR DESCRIPTION
**Pull request by etiotto**
Fixes #1622

### CODE REVIEW

File: third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp [hunk 1]
```diff
@@ -388,6 +392,13 @@ class ScfPattern : public OpRewritePattern<scf::ForOp> {
     for (Operation *deleteOp : deleteList)
       rewriter.eraseOp(deleteOp);
 
+    //    llvm::errs() << "forOp:\n" << forOp << "\n";
```
Comment (etiotto) [inline third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp]: remove

File: third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp [hunk 2]
```diff
@@ -361,6 +361,9 @@ class ScfPattern : public OpRewritePattern<scf::ForOp> {
     rewriter.create<scf::YieldOp>(yield.getLoc(), newValues);
     rewriter.eraseOp(yield);
 
+    auto mod = forOp->getParentOfType<ModuleOp>();
```
Comment (etiotto) [inline third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp]: remove

File: third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp (hunk 1 above)
Comment (etiotto) [reply third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp]: done

File: third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp (hunk 2 above)
Comment (etiotto) [reply third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp]: done

**Review by whitneywhtsang — APPROVED** [review]

File: third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp [hunk 3]
```diff
@@ -412,11 +413,17 @@ class ScfPattern : public OpRewritePattern<scf::ForOp> {
 
       if (llvm::any_of(arg.getUsers(), [](Operation *user) {
             return !isa<ttgi::ExtractOp>(user);
-          })) {
+          }))
         return false;
-      }
     }
 
+    // Bail out if any user of the loop result is not an 'extract' operation.
```
Comment (Dewei-Wang-sh) [inline third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp:420]: not the way we want.
we can have loop results that result0's user is extract, result1's user is not extract, and still this should work.

Comment (etiotto) [reply third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp:420]: Right, the comment is misleading because the code bails out only if the loop yields a single result.

Comment (etiotto) [reply third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp]: Comment clarified.
